### ISSUE TITLE
[Utilities.IoC] BadImageFormatException Unhandled

### ISSUE THREAD

**Issue by captkirk88** [JaCraig/Craig-s-Utility-Library#9]
IoC Manager attempts to load a native DLL thinking it is a Managed DLL.
```csharp

System.BadImageFormatException: Could not load file or assembly 'freetype6.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Utilities.IoC.Manager.<>c.<LoadAssemblies>b__13_2(FileInfo x) in Manager.cs:line 167
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Utilities.IoC.Manager.LoadAssemblies() in Manager.cs:line 167
   at Utilities.IoC.Manager..ctor() in Manager.cs:line 44
   at Utilities.IoC.Manager..cctor() in Manager.cs:line 64
```

**Comment by JaCraig** [comment]
Should be fixed with latest version.
